name: Build and Release

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.x'  # Change this to the .NET version your project uses

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and publish
      run: |
        dotnet publish swex-filter/swex-filter.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained true -o ./output/swex-filter

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: swex-filter
        path: ./output/swex-filter/swex-filter.exe

    - name: Package artifact as NuGet
      run: |
        cd ./output/swex-filter/
        nuget init .
        nuget pack swex-filter.csproj -OutputDirectory .

    - name: Publish to GitHub Packages
      run: dotnet nuget push ./output/swex-filter/*.nupkg -k ${{ secrets.SWEX_FILTER_PACKAGES_TOKEN }} -s https://nuget.pkg.github.com/Volminoduro/index.json